[package]
name = "omniman-clipboard"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
omniman-core = { path = "../omniman-core" }
rusqlite = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
aes-gcm = { workspace = true }
getrandom = { workspace = true }
secret-service = { workspace = true }
base64 = { workspace = true }
